name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if version has changed
        id: check_version
        run: |
          VERSION=$(grep -oP "Version:\s*\K\d+(\.\d+)*" wcpos-{{GATEWAY_SLUG}}.php)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git fetch --prune --unshallow
          if git tag | grep -q "v$VERSION"; then
            echo "Version has not changed. Skipping release..."
            echo "release=false" >> $GITHUB_OUTPUT
          else
            echo "Version has changed. Creating new release..."
            echo "release=true" >> $GITHUB_OUTPUT
          fi

      - name: Build ZIP
        if: steps.check_version.outputs.release == 'true'
        run: |
          zip -r "woocommerce-pos-{{GATEWAY_SLUG}}-gateway.zip" . \
            -x "*.git*" \
            -x "create-gateway.sh" \
            -x "demo.sh" \
            -x "PLUGIN_README.md" \
            -x "demo-output/*"

      - name: Create Release
        if: steps.check_version.outputs.release == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          files: woocommerce-pos-{{GATEWAY_SLUG}}-gateway.zip
